# Generated by Django 5.1.5 on 2025-01-18 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.TextField()),
                ('position', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTION', 'Rejection')], max_length=10)),
            ],
        ),
    ]
